info:
  contact: {}
paths:
  /api/v1/admin/create-user:
    post:
      consumes:
      - application/json
      description: 管理员创建新用户账号，可以指定用户角色和是否为管理员账户
      parameters:
      - description: 用户名，建议使用姓名拼音
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: 用户昵称，请使用真实姓名
        in: body
        name: nick_name
        required: true
        schema:
          type: string
      - description: 手机号
        in: body
        name: phone
        required: true
        schema:
          type: string
      - description: 邮箱
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 用户角色，student 学生或 teacher 老师
        enum:
        - student
        - teacher
        in: body
        name: role
        required: true
        schema:
          type: string
      - description: 是否是管理员
        in: body
        name: is_admin
        required: true
        schema:
          type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 创建新用户
      tags:
      - admin
  /api/v1/record:
    get:
      consumes:
      - application/json
      description: 黄雪朋的学习swagger的过程
      parameters:
      - description: 下面填写手机号码
        in: body
        name: mobile
        required: true
        schema:
          type: string
      - description: 填写密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 测试swagger
      tags:
      - 黄雪朋的测试接口
swagger: "2.0"
